### ISSUE TITLE
Allow model gpt-4-1106-preview and ideally any

### ISSUE THREAD

**Issue by bittylicious** [jack482653/openai-slack-bot#20]
It would be great to alter models.js to allow the new GPT-4 turbo model.

What would be even better is if we could just supply the model and API type in the docker/yarn command, if we can't find it, just give it a go with the OpenAI API.

**Comment by jack482653** [comment]
Sure, I will remove the restriction of model name for easier use.

**Comment by jack482653** [comment]
I have release v1.11.0, which supports gpt-4-1106-preview model.
Also you can switch using model via changing `OPENAI_CHAT_MODEL` at .env file.

Please let me know if it has any problem.

**Comment by bittylicious** [comment]
Works a treat, thank you very much!
